
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ToolVersion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ToolVersion
 * 
 */
export type ToolVersionModel = runtime.Types.Result.DefaultSelection<Prisma.$ToolVersionPayload>

export type AggregateToolVersion = {
  _count: ToolVersionCountAggregateOutputType | null
  _avg: ToolVersionAvgAggregateOutputType | null
  _sum: ToolVersionSumAggregateOutputType | null
  _min: ToolVersionMinAggregateOutputType | null
  _max: ToolVersionMaxAggregateOutputType | null
}

export type ToolVersionAvgAggregateOutputType = {
  id: number | null
  width: number | null
  height: number | null
  x: number | null
  y: number | null
}

export type ToolVersionSumAggregateOutputType = {
  id: number | null
  width: number | null
  height: number | null
  x: number | null
  y: number | null
}

export type ToolVersionMinAggregateOutputType = {
  id: number | null
  nodeId: string | null
  parentId: string | null
  path: string | null
  validFrom: Date | null
  validTo: Date | null
  name: string | null
  width: number | null
  height: number | null
  x: number | null
  y: number | null
  createdAt: Date | null
}

export type ToolVersionMaxAggregateOutputType = {
  id: number | null
  nodeId: string | null
  parentId: string | null
  path: string | null
  validFrom: Date | null
  validTo: Date | null
  name: string | null
  width: number | null
  height: number | null
  x: number | null
  y: number | null
  createdAt: Date | null
}

export type ToolVersionCountAggregateOutputType = {
  id: number
  nodeId: number
  parentId: number
  path: number
  validFrom: number
  validTo: number
  name: number
  width: number
  height: number
  x: number
  y: number
  createdAt: number
  _all: number
}


export type ToolVersionAvgAggregateInputType = {
  id?: true
  width?: true
  height?: true
  x?: true
  y?: true
}

export type ToolVersionSumAggregateInputType = {
  id?: true
  width?: true
  height?: true
  x?: true
  y?: true
}

export type ToolVersionMinAggregateInputType = {
  id?: true
  nodeId?: true
  parentId?: true
  path?: true
  validFrom?: true
  validTo?: true
  name?: true
  width?: true
  height?: true
  x?: true
  y?: true
  createdAt?: true
}

export type ToolVersionMaxAggregateInputType = {
  id?: true
  nodeId?: true
  parentId?: true
  path?: true
  validFrom?: true
  validTo?: true
  name?: true
  width?: true
  height?: true
  x?: true
  y?: true
  createdAt?: true
}

export type ToolVersionCountAggregateInputType = {
  id?: true
  nodeId?: true
  parentId?: true
  path?: true
  validFrom?: true
  validTo?: true
  name?: true
  width?: true
  height?: true
  x?: true
  y?: true
  createdAt?: true
  _all?: true
}

export type ToolVersionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolVersion to aggregate.
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolVersions to fetch.
   */
  orderBy?: Prisma.ToolVersionOrderByWithRelationInput | Prisma.ToolVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ToolVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ToolVersions
  **/
  _count?: true | ToolVersionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ToolVersionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ToolVersionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ToolVersionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ToolVersionMaxAggregateInputType
}

export type GetToolVersionAggregateType<T extends ToolVersionAggregateArgs> = {
      [P in keyof T & keyof AggregateToolVersion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateToolVersion[P]>
    : Prisma.GetScalarType<T[P], AggregateToolVersion[P]>
}




export type ToolVersionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ToolVersionWhereInput
  orderBy?: Prisma.ToolVersionOrderByWithAggregationInput | Prisma.ToolVersionOrderByWithAggregationInput[]
  by: Prisma.ToolVersionScalarFieldEnum[] | Prisma.ToolVersionScalarFieldEnum
  having?: Prisma.ToolVersionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ToolVersionCountAggregateInputType | true
  _avg?: ToolVersionAvgAggregateInputType
  _sum?: ToolVersionSumAggregateInputType
  _min?: ToolVersionMinAggregateInputType
  _max?: ToolVersionMaxAggregateInputType
}

export type ToolVersionGroupByOutputType = {
  id: number
  nodeId: string
  parentId: string | null
  path: string
  validFrom: Date
  validTo: Date | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt: Date
  _count: ToolVersionCountAggregateOutputType | null
  _avg: ToolVersionAvgAggregateOutputType | null
  _sum: ToolVersionSumAggregateOutputType | null
  _min: ToolVersionMinAggregateOutputType | null
  _max: ToolVersionMaxAggregateOutputType | null
}

type GetToolVersionGroupByPayload<T extends ToolVersionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ToolVersionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ToolVersionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ToolVersionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ToolVersionGroupByOutputType[P]>
      }
    >
  >



export type ToolVersionWhereInput = {
  AND?: Prisma.ToolVersionWhereInput | Prisma.ToolVersionWhereInput[]
  OR?: Prisma.ToolVersionWhereInput[]
  NOT?: Prisma.ToolVersionWhereInput | Prisma.ToolVersionWhereInput[]
  id?: Prisma.IntFilter<"ToolVersion"> | number
  nodeId?: Prisma.StringFilter<"ToolVersion"> | string
  parentId?: Prisma.StringNullableFilter<"ToolVersion"> | string | null
  path?: Prisma.StringFilter<"ToolVersion"> | string
  validFrom?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ToolVersion"> | Date | string | null
  name?: Prisma.StringFilter<"ToolVersion"> | string
  width?: Prisma.IntFilter<"ToolVersion"> | number
  height?: Prisma.IntFilter<"ToolVersion"> | number
  x?: Prisma.IntFilter<"ToolVersion"> | number
  y?: Prisma.IntFilter<"ToolVersion"> | number
  createdAt?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
  node?: Prisma.XOR<Prisma.ToolScalarRelationFilter, Prisma.ToolWhereInput>
  parent?: Prisma.XOR<Prisma.ToolNullableScalarRelationFilter, Prisma.ToolWhereInput> | null
}

export type ToolVersionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  path?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  node?: Prisma.ToolOrderByWithRelationInput
  parent?: Prisma.ToolOrderByWithRelationInput
  _relevance?: Prisma.ToolVersionOrderByRelevanceInput
}

export type ToolVersionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ToolVersionWhereInput | Prisma.ToolVersionWhereInput[]
  OR?: Prisma.ToolVersionWhereInput[]
  NOT?: Prisma.ToolVersionWhereInput | Prisma.ToolVersionWhereInput[]
  nodeId?: Prisma.StringFilter<"ToolVersion"> | string
  parentId?: Prisma.StringNullableFilter<"ToolVersion"> | string | null
  path?: Prisma.StringFilter<"ToolVersion"> | string
  validFrom?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ToolVersion"> | Date | string | null
  name?: Prisma.StringFilter<"ToolVersion"> | string
  width?: Prisma.IntFilter<"ToolVersion"> | number
  height?: Prisma.IntFilter<"ToolVersion"> | number
  x?: Prisma.IntFilter<"ToolVersion"> | number
  y?: Prisma.IntFilter<"ToolVersion"> | number
  createdAt?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
  node?: Prisma.XOR<Prisma.ToolScalarRelationFilter, Prisma.ToolWhereInput>
  parent?: Prisma.XOR<Prisma.ToolNullableScalarRelationFilter, Prisma.ToolWhereInput> | null
}, "id">

export type ToolVersionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  path?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ToolVersionCountOrderByAggregateInput
  _avg?: Prisma.ToolVersionAvgOrderByAggregateInput
  _max?: Prisma.ToolVersionMaxOrderByAggregateInput
  _min?: Prisma.ToolVersionMinOrderByAggregateInput
  _sum?: Prisma.ToolVersionSumOrderByAggregateInput
}

export type ToolVersionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ToolVersionScalarWhereWithAggregatesInput | Prisma.ToolVersionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ToolVersionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ToolVersionScalarWhereWithAggregatesInput | Prisma.ToolVersionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ToolVersion"> | number
  nodeId?: Prisma.StringWithAggregatesFilter<"ToolVersion"> | string
  parentId?: Prisma.StringNullableWithAggregatesFilter<"ToolVersion"> | string | null
  path?: Prisma.StringWithAggregatesFilter<"ToolVersion"> | string
  validFrom?: Prisma.DateTimeWithAggregatesFilter<"ToolVersion"> | Date | string
  validTo?: Prisma.DateTimeNullableWithAggregatesFilter<"ToolVersion"> | Date | string | null
  name?: Prisma.StringWithAggregatesFilter<"ToolVersion"> | string
  width?: Prisma.IntWithAggregatesFilter<"ToolVersion"> | number
  height?: Prisma.IntWithAggregatesFilter<"ToolVersion"> | number
  x?: Prisma.IntWithAggregatesFilter<"ToolVersion"> | number
  y?: Prisma.IntWithAggregatesFilter<"ToolVersion"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ToolVersion"> | Date | string
}

export type ToolVersionCreateInput = {
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
  node: Prisma.ToolCreateNestedOneWithoutVersionsInput
  parent?: Prisma.ToolCreateNestedOneWithoutChildrenVersionInput
}

export type ToolVersionUncheckedCreateInput = {
  id?: number
  nodeId: string
  parentId?: string | null
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionUpdateInput = {
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  node?: Prisma.ToolUpdateOneRequiredWithoutVersionsNestedInput
  parent?: Prisma.ToolUpdateOneWithoutChildrenVersionNestedInput
}

export type ToolVersionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionCreateManyInput = {
  id?: number
  nodeId: string
  parentId?: string | null
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionUpdateManyMutationInput = {
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionListRelationFilter = {
  every?: Prisma.ToolVersionWhereInput
  some?: Prisma.ToolVersionWhereInput
  none?: Prisma.ToolVersionWhereInput
}

export type ToolVersionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ToolVersionOrderByRelevanceInput = {
  fields: Prisma.ToolVersionOrderByRelevanceFieldEnum | Prisma.ToolVersionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ToolVersionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  name?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolVersionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
}

export type ToolVersionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  name?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolVersionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  name?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolVersionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
}

export type ToolVersionCreateNestedManyWithoutNodeInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput> | Prisma.ToolVersionCreateWithoutNodeInput[] | Prisma.ToolVersionUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutNodeInput | Prisma.ToolVersionCreateOrConnectWithoutNodeInput[]
  createMany?: Prisma.ToolVersionCreateManyNodeInputEnvelope
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
}

export type ToolVersionCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput> | Prisma.ToolVersionCreateWithoutParentInput[] | Prisma.ToolVersionUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutParentInput | Prisma.ToolVersionCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.ToolVersionCreateManyParentInputEnvelope
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
}

export type ToolVersionUncheckedCreateNestedManyWithoutNodeInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput> | Prisma.ToolVersionCreateWithoutNodeInput[] | Prisma.ToolVersionUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutNodeInput | Prisma.ToolVersionCreateOrConnectWithoutNodeInput[]
  createMany?: Prisma.ToolVersionCreateManyNodeInputEnvelope
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
}

export type ToolVersionUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput> | Prisma.ToolVersionCreateWithoutParentInput[] | Prisma.ToolVersionUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutParentInput | Prisma.ToolVersionCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.ToolVersionCreateManyParentInputEnvelope
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
}

export type ToolVersionUpdateManyWithoutNodeNestedInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput> | Prisma.ToolVersionCreateWithoutNodeInput[] | Prisma.ToolVersionUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutNodeInput | Prisma.ToolVersionCreateOrConnectWithoutNodeInput[]
  upsert?: Prisma.ToolVersionUpsertWithWhereUniqueWithoutNodeInput | Prisma.ToolVersionUpsertWithWhereUniqueWithoutNodeInput[]
  createMany?: Prisma.ToolVersionCreateManyNodeInputEnvelope
  set?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  disconnect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  delete?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  update?: Prisma.ToolVersionUpdateWithWhereUniqueWithoutNodeInput | Prisma.ToolVersionUpdateWithWhereUniqueWithoutNodeInput[]
  updateMany?: Prisma.ToolVersionUpdateManyWithWhereWithoutNodeInput | Prisma.ToolVersionUpdateManyWithWhereWithoutNodeInput[]
  deleteMany?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
}

export type ToolVersionUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput> | Prisma.ToolVersionCreateWithoutParentInput[] | Prisma.ToolVersionUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutParentInput | Prisma.ToolVersionCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.ToolVersionUpsertWithWhereUniqueWithoutParentInput | Prisma.ToolVersionUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.ToolVersionCreateManyParentInputEnvelope
  set?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  disconnect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  delete?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  update?: Prisma.ToolVersionUpdateWithWhereUniqueWithoutParentInput | Prisma.ToolVersionUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.ToolVersionUpdateManyWithWhereWithoutParentInput | Prisma.ToolVersionUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
}

export type ToolVersionUncheckedUpdateManyWithoutNodeNestedInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput> | Prisma.ToolVersionCreateWithoutNodeInput[] | Prisma.ToolVersionUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutNodeInput | Prisma.ToolVersionCreateOrConnectWithoutNodeInput[]
  upsert?: Prisma.ToolVersionUpsertWithWhereUniqueWithoutNodeInput | Prisma.ToolVersionUpsertWithWhereUniqueWithoutNodeInput[]
  createMany?: Prisma.ToolVersionCreateManyNodeInputEnvelope
  set?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  disconnect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  delete?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  update?: Prisma.ToolVersionUpdateWithWhereUniqueWithoutNodeInput | Prisma.ToolVersionUpdateWithWhereUniqueWithoutNodeInput[]
  updateMany?: Prisma.ToolVersionUpdateManyWithWhereWithoutNodeInput | Prisma.ToolVersionUpdateManyWithWhereWithoutNodeInput[]
  deleteMany?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
}

export type ToolVersionUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput> | Prisma.ToolVersionCreateWithoutParentInput[] | Prisma.ToolVersionUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ToolVersionCreateOrConnectWithoutParentInput | Prisma.ToolVersionCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.ToolVersionUpsertWithWhereUniqueWithoutParentInput | Prisma.ToolVersionUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.ToolVersionCreateManyParentInputEnvelope
  set?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  disconnect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  delete?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  connect?: Prisma.ToolVersionWhereUniqueInput | Prisma.ToolVersionWhereUniqueInput[]
  update?: Prisma.ToolVersionUpdateWithWhereUniqueWithoutParentInput | Prisma.ToolVersionUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.ToolVersionUpdateManyWithWhereWithoutParentInput | Prisma.ToolVersionUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type ToolVersionCreateWithoutNodeInput = {
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
  parent?: Prisma.ToolCreateNestedOneWithoutChildrenVersionInput
}

export type ToolVersionUncheckedCreateWithoutNodeInput = {
  id?: number
  parentId?: string | null
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionCreateOrConnectWithoutNodeInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput>
}

export type ToolVersionCreateManyNodeInputEnvelope = {
  data: Prisma.ToolVersionCreateManyNodeInput | Prisma.ToolVersionCreateManyNodeInput[]
  skipDuplicates?: boolean
}

export type ToolVersionCreateWithoutParentInput = {
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
  node: Prisma.ToolCreateNestedOneWithoutVersionsInput
}

export type ToolVersionUncheckedCreateWithoutParentInput = {
  id?: number
  nodeId: string
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionCreateOrConnectWithoutParentInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput>
}

export type ToolVersionCreateManyParentInputEnvelope = {
  data: Prisma.ToolVersionCreateManyParentInput | Prisma.ToolVersionCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type ToolVersionUpsertWithWhereUniqueWithoutNodeInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  update: Prisma.XOR<Prisma.ToolVersionUpdateWithoutNodeInput, Prisma.ToolVersionUncheckedUpdateWithoutNodeInput>
  create: Prisma.XOR<Prisma.ToolVersionCreateWithoutNodeInput, Prisma.ToolVersionUncheckedCreateWithoutNodeInput>
}

export type ToolVersionUpdateWithWhereUniqueWithoutNodeInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  data: Prisma.XOR<Prisma.ToolVersionUpdateWithoutNodeInput, Prisma.ToolVersionUncheckedUpdateWithoutNodeInput>
}

export type ToolVersionUpdateManyWithWhereWithoutNodeInput = {
  where: Prisma.ToolVersionScalarWhereInput
  data: Prisma.XOR<Prisma.ToolVersionUpdateManyMutationInput, Prisma.ToolVersionUncheckedUpdateManyWithoutNodeInput>
}

export type ToolVersionScalarWhereInput = {
  AND?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
  OR?: Prisma.ToolVersionScalarWhereInput[]
  NOT?: Prisma.ToolVersionScalarWhereInput | Prisma.ToolVersionScalarWhereInput[]
  id?: Prisma.IntFilter<"ToolVersion"> | number
  nodeId?: Prisma.StringFilter<"ToolVersion"> | string
  parentId?: Prisma.StringNullableFilter<"ToolVersion"> | string | null
  path?: Prisma.StringFilter<"ToolVersion"> | string
  validFrom?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ToolVersion"> | Date | string | null
  name?: Prisma.StringFilter<"ToolVersion"> | string
  width?: Prisma.IntFilter<"ToolVersion"> | number
  height?: Prisma.IntFilter<"ToolVersion"> | number
  x?: Prisma.IntFilter<"ToolVersion"> | number
  y?: Prisma.IntFilter<"ToolVersion"> | number
  createdAt?: Prisma.DateTimeFilter<"ToolVersion"> | Date | string
}

export type ToolVersionUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  update: Prisma.XOR<Prisma.ToolVersionUpdateWithoutParentInput, Prisma.ToolVersionUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.ToolVersionCreateWithoutParentInput, Prisma.ToolVersionUncheckedCreateWithoutParentInput>
}

export type ToolVersionUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.ToolVersionWhereUniqueInput
  data: Prisma.XOR<Prisma.ToolVersionUpdateWithoutParentInput, Prisma.ToolVersionUncheckedUpdateWithoutParentInput>
}

export type ToolVersionUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.ToolVersionScalarWhereInput
  data: Prisma.XOR<Prisma.ToolVersionUpdateManyMutationInput, Prisma.ToolVersionUncheckedUpdateManyWithoutParentInput>
}

export type ToolVersionCreateManyNodeInput = {
  id?: number
  parentId?: string | null
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionCreateManyParentInput = {
  id?: number
  nodeId: string
  path: string
  validFrom: Date | string
  validTo?: Date | string | null
  name: string
  width: number
  height: number
  x: number
  y: number
  createdAt?: Date | string
}

export type ToolVersionUpdateWithoutNodeInput = {
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.ToolUpdateOneWithoutChildrenVersionNestedInput
}

export type ToolVersionUncheckedUpdateWithoutNodeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionUncheckedUpdateManyWithoutNodeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionUpdateWithoutParentInput = {
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  node?: Prisma.ToolUpdateOneRequiredWithoutVersionsNestedInput
}

export type ToolVersionUncheckedUpdateWithoutParentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolVersionUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  height?: Prisma.IntFieldUpdateOperationsInput | number
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ToolVersionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nodeId?: boolean
  parentId?: boolean
  path?: boolean
  validFrom?: boolean
  validTo?: boolean
  name?: boolean
  width?: boolean
  height?: boolean
  x?: boolean
  y?: boolean
  createdAt?: boolean
  node?: boolean | Prisma.ToolDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.ToolVersion$parentArgs<ExtArgs>
}, ExtArgs["result"]["toolVersion"]>



export type ToolVersionSelectScalar = {
  id?: boolean
  nodeId?: boolean
  parentId?: boolean
  path?: boolean
  validFrom?: boolean
  validTo?: boolean
  name?: boolean
  width?: boolean
  height?: boolean
  x?: boolean
  y?: boolean
  createdAt?: boolean
}

export type ToolVersionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nodeId" | "parentId" | "path" | "validFrom" | "validTo" | "name" | "width" | "height" | "x" | "y" | "createdAt", ExtArgs["result"]["toolVersion"]>
export type ToolVersionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  node?: boolean | Prisma.ToolDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.ToolVersion$parentArgs<ExtArgs>
}

export type $ToolVersionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ToolVersion"
  objects: {
    node: Prisma.$ToolPayload<ExtArgs>
    parent: Prisma.$ToolPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nodeId: string
    parentId: string | null
    path: string
    validFrom: Date
    validTo: Date | null
    name: string
    width: number
    height: number
    x: number
    y: number
    createdAt: Date
  }, ExtArgs["result"]["toolVersion"]>
  composites: {}
}

export type ToolVersionGetPayload<S extends boolean | null | undefined | ToolVersionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload, S>

export type ToolVersionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ToolVersionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ToolVersionCountAggregateInputType | true
  }

export interface ToolVersionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ToolVersion'], meta: { name: 'ToolVersion' } }
  /**
   * Find zero or one ToolVersion that matches the filter.
   * @param {ToolVersionFindUniqueArgs} args - Arguments to find a ToolVersion
   * @example
   * // Get one ToolVersion
   * const toolVersion = await prisma.toolVersion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ToolVersionFindUniqueArgs>(args: Prisma.SelectSubset<T, ToolVersionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ToolVersion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ToolVersionFindUniqueOrThrowArgs} args - Arguments to find a ToolVersion
   * @example
   * // Get one ToolVersion
   * const toolVersion = await prisma.toolVersion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ToolVersionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ToolVersionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolVersion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionFindFirstArgs} args - Arguments to find a ToolVersion
   * @example
   * // Get one ToolVersion
   * const toolVersion = await prisma.toolVersion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ToolVersionFindFirstArgs>(args?: Prisma.SelectSubset<T, ToolVersionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolVersion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionFindFirstOrThrowArgs} args - Arguments to find a ToolVersion
   * @example
   * // Get one ToolVersion
   * const toolVersion = await prisma.toolVersion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ToolVersionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ToolVersionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ToolVersions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ToolVersions
   * const toolVersions = await prisma.toolVersion.findMany()
   * 
   * // Get first 10 ToolVersions
   * const toolVersions = await prisma.toolVersion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const toolVersionWithIdOnly = await prisma.toolVersion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ToolVersionFindManyArgs>(args?: Prisma.SelectSubset<T, ToolVersionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ToolVersion.
   * @param {ToolVersionCreateArgs} args - Arguments to create a ToolVersion.
   * @example
   * // Create one ToolVersion
   * const ToolVersion = await prisma.toolVersion.create({
   *   data: {
   *     // ... data to create a ToolVersion
   *   }
   * })
   * 
   */
  create<T extends ToolVersionCreateArgs>(args: Prisma.SelectSubset<T, ToolVersionCreateArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ToolVersions.
   * @param {ToolVersionCreateManyArgs} args - Arguments to create many ToolVersions.
   * @example
   * // Create many ToolVersions
   * const toolVersion = await prisma.toolVersion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ToolVersionCreateManyArgs>(args?: Prisma.SelectSubset<T, ToolVersionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ToolVersion.
   * @param {ToolVersionDeleteArgs} args - Arguments to delete one ToolVersion.
   * @example
   * // Delete one ToolVersion
   * const ToolVersion = await prisma.toolVersion.delete({
   *   where: {
   *     // ... filter to delete one ToolVersion
   *   }
   * })
   * 
   */
  delete<T extends ToolVersionDeleteArgs>(args: Prisma.SelectSubset<T, ToolVersionDeleteArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ToolVersion.
   * @param {ToolVersionUpdateArgs} args - Arguments to update one ToolVersion.
   * @example
   * // Update one ToolVersion
   * const toolVersion = await prisma.toolVersion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ToolVersionUpdateArgs>(args: Prisma.SelectSubset<T, ToolVersionUpdateArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ToolVersions.
   * @param {ToolVersionDeleteManyArgs} args - Arguments to filter ToolVersions to delete.
   * @example
   * // Delete a few ToolVersions
   * const { count } = await prisma.toolVersion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ToolVersionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ToolVersionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ToolVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ToolVersions
   * const toolVersion = await prisma.toolVersion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ToolVersionUpdateManyArgs>(args: Prisma.SelectSubset<T, ToolVersionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ToolVersion.
   * @param {ToolVersionUpsertArgs} args - Arguments to update or create a ToolVersion.
   * @example
   * // Update or create a ToolVersion
   * const toolVersion = await prisma.toolVersion.upsert({
   *   create: {
   *     // ... data to create a ToolVersion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ToolVersion we want to update
   *   }
   * })
   */
  upsert<T extends ToolVersionUpsertArgs>(args: Prisma.SelectSubset<T, ToolVersionUpsertArgs<ExtArgs>>): Prisma.Prisma__ToolVersionClient<runtime.Types.Result.GetResult<Prisma.$ToolVersionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ToolVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionCountArgs} args - Arguments to filter ToolVersions to count.
   * @example
   * // Count the number of ToolVersions
   * const count = await prisma.toolVersion.count({
   *   where: {
   *     // ... the filter for the ToolVersions we want to count
   *   }
   * })
  **/
  count<T extends ToolVersionCountArgs>(
    args?: Prisma.Subset<T, ToolVersionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ToolVersionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ToolVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ToolVersionAggregateArgs>(args: Prisma.Subset<T, ToolVersionAggregateArgs>): Prisma.PrismaPromise<GetToolVersionAggregateType<T>>

  /**
   * Group by ToolVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolVersionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ToolVersionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ToolVersionGroupByArgs['orderBy'] }
      : { orderBy?: ToolVersionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ToolVersionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetToolVersionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ToolVersion model
 */
readonly fields: ToolVersionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ToolVersion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ToolVersionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  node<T extends Prisma.ToolDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ToolDefaultArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  parent<T extends Prisma.ToolVersion$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ToolVersion$parentArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ToolVersion model
 */
export interface ToolVersionFieldRefs {
  readonly id: Prisma.FieldRef<"ToolVersion", 'Int'>
  readonly nodeId: Prisma.FieldRef<"ToolVersion", 'String'>
  readonly parentId: Prisma.FieldRef<"ToolVersion", 'String'>
  readonly path: Prisma.FieldRef<"ToolVersion", 'String'>
  readonly validFrom: Prisma.FieldRef<"ToolVersion", 'DateTime'>
  readonly validTo: Prisma.FieldRef<"ToolVersion", 'DateTime'>
  readonly name: Prisma.FieldRef<"ToolVersion", 'String'>
  readonly width: Prisma.FieldRef<"ToolVersion", 'Int'>
  readonly height: Prisma.FieldRef<"ToolVersion", 'Int'>
  readonly x: Prisma.FieldRef<"ToolVersion", 'Int'>
  readonly y: Prisma.FieldRef<"ToolVersion", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ToolVersion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ToolVersion findUnique
 */
export type ToolVersionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter, which ToolVersion to fetch.
   */
  where: Prisma.ToolVersionWhereUniqueInput
}

/**
 * ToolVersion findUniqueOrThrow
 */
export type ToolVersionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter, which ToolVersion to fetch.
   */
  where: Prisma.ToolVersionWhereUniqueInput
}

/**
 * ToolVersion findFirst
 */
export type ToolVersionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter, which ToolVersion to fetch.
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolVersions to fetch.
   */
  orderBy?: Prisma.ToolVersionOrderByWithRelationInput | Prisma.ToolVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolVersions.
   */
  cursor?: Prisma.ToolVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolVersions.
   */
  distinct?: Prisma.ToolVersionScalarFieldEnum | Prisma.ToolVersionScalarFieldEnum[]
}

/**
 * ToolVersion findFirstOrThrow
 */
export type ToolVersionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter, which ToolVersion to fetch.
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolVersions to fetch.
   */
  orderBy?: Prisma.ToolVersionOrderByWithRelationInput | Prisma.ToolVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolVersions.
   */
  cursor?: Prisma.ToolVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolVersions.
   */
  distinct?: Prisma.ToolVersionScalarFieldEnum | Prisma.ToolVersionScalarFieldEnum[]
}

/**
 * ToolVersion findMany
 */
export type ToolVersionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter, which ToolVersions to fetch.
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolVersions to fetch.
   */
  orderBy?: Prisma.ToolVersionOrderByWithRelationInput | Prisma.ToolVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ToolVersions.
   */
  cursor?: Prisma.ToolVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolVersions.
   */
  skip?: number
  distinct?: Prisma.ToolVersionScalarFieldEnum | Prisma.ToolVersionScalarFieldEnum[]
}

/**
 * ToolVersion create
 */
export type ToolVersionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * The data needed to create a ToolVersion.
   */
  data: Prisma.XOR<Prisma.ToolVersionCreateInput, Prisma.ToolVersionUncheckedCreateInput>
}

/**
 * ToolVersion createMany
 */
export type ToolVersionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ToolVersions.
   */
  data: Prisma.ToolVersionCreateManyInput | Prisma.ToolVersionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ToolVersion update
 */
export type ToolVersionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * The data needed to update a ToolVersion.
   */
  data: Prisma.XOR<Prisma.ToolVersionUpdateInput, Prisma.ToolVersionUncheckedUpdateInput>
  /**
   * Choose, which ToolVersion to update.
   */
  where: Prisma.ToolVersionWhereUniqueInput
}

/**
 * ToolVersion updateMany
 */
export type ToolVersionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ToolVersions.
   */
  data: Prisma.XOR<Prisma.ToolVersionUpdateManyMutationInput, Prisma.ToolVersionUncheckedUpdateManyInput>
  /**
   * Filter which ToolVersions to update
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * Limit how many ToolVersions to update.
   */
  limit?: number
}

/**
 * ToolVersion upsert
 */
export type ToolVersionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * The filter to search for the ToolVersion to update in case it exists.
   */
  where: Prisma.ToolVersionWhereUniqueInput
  /**
   * In case the ToolVersion found by the `where` argument doesn't exist, create a new ToolVersion with this data.
   */
  create: Prisma.XOR<Prisma.ToolVersionCreateInput, Prisma.ToolVersionUncheckedCreateInput>
  /**
   * In case the ToolVersion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ToolVersionUpdateInput, Prisma.ToolVersionUncheckedUpdateInput>
}

/**
 * ToolVersion delete
 */
export type ToolVersionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
  /**
   * Filter which ToolVersion to delete.
   */
  where: Prisma.ToolVersionWhereUniqueInput
}

/**
 * ToolVersion deleteMany
 */
export type ToolVersionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolVersions to delete
   */
  where?: Prisma.ToolVersionWhereInput
  /**
   * Limit how many ToolVersions to delete.
   */
  limit?: number
}

/**
 * ToolVersion.parent
 */
export type ToolVersion$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  where?: Prisma.ToolWhereInput
}

/**
 * ToolVersion without action
 */
export type ToolVersionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolVersion
   */
  select?: Prisma.ToolVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolVersion
   */
  omit?: Prisma.ToolVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolVersionInclude<ExtArgs> | null
}
